name: Add Drop Alert

on:
  workflow_dispatch:
  schedule:
    - cron: '30 * * * *'

jobs:
  my-job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install the project
      run: uv sync --all-extras --dev


    - name: Run gmail alert script
      env:
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        JIIT_USERNAME: ${{ secrets.JIIT_USERNAME }}
        JIIT_PASSWORD: ${{ secrets.JIIT_PASSWORD }}
        OAUTH2_CREDS: ${{ secrets.OAUTH2_CREDS }}
      run: |
        echo "$OAUTH2_CREDS" > "~/oauth2_creds.json"
        uv run gmail_alert.py

# update the secrets after running the script. no need to update at the beginning,
# because the very first job is initialised with latest secrets set manually.
# subsequent runs save latest secrets at the end of running everything.
    - name: Generate minified OAUTH2_CREDS
      run: cat ~/oauth2_creds.json | jq -c . > minified_oauth2_creds.json

    - uses: qoomon/actions--access-token@v3
      id: access-token
      with:
        permissions: |
            secrets: write

    - name: Update secret
      run: >-
        gh secret
        set 'OAUTH2_CREDS'
        --body "$(cat minified_oauth2_creds.json)"
        --repo ${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ steps.access-token.outputs.token }}
